import 'package:flutter/material.dart';

class AppThemes {
  // CONFIG - LIGHT THEME
  static final lightTheme = ThemeData(
    // // bool? applyElevationOverlayColor,
    // // NoDefaultCupertinoThemeData? cupertinoOverrideTheme,
    // // Iterable<ThemeExtension<dynamic>>? extensions,
    // // inputDecorationTheme: InputDecorationThemeStyles.inputDecorationTheme,
    // // MaterialTapTargetSize? materialTapTargetSize,
    // // PageTransitionsTheme? pageTransitionsTheme,
    // // TargetPlatform? platform,
    // // ScrollbarThemeData? scrollbarTheme,
    // // InteractiveInkFeatureFactory? splashFactory,
    // useMaterial3: false,
    // // VisualDensity? visualDensity,
    // brightness: Brightness.light,
    // canvasColor: AppColors.canvasColor,
    // cardColor: AppColors.cardColor,
    colorScheme: ColorScheme.fromSeed(
      seedColor: Colors.green,
    ),
    // colorScheme: const ColorScheme(
    //   brightness: Brightness.light,
    //   primary: AppColors.primaryColor,
    //   onPrimary: AppColors.onPrimaryColor,
    //   // Color? primaryContainer,
    //   // Color? onPrimaryContainer,
    //   secondary: AppColors.secondaryColor,
    //   onSecondary: AppColors.onSecondaryColor,
    //   // Color? secondaryContainer,
    //   // Color? onSecondaryContainer,
    //   // Color? tertiary,
    //   // Color? onTertiary,
    //   // Color? tertiaryContainer,
    //   // Color? onTertiaryContainer,
    //   error: AppColors.errorColor,
    //   onError: AppColors.onErrorColor,
    //   // Color? errorContainer,
    //   // Color? onErrorContainer,
    //   background: AppColors.backgroundColor,
    //   onBackground: AppColors.onBackgroundColor,
    //   surface: AppColors.surfaceColor,
    //   onSurface: AppColors.primaryMaterialColor,
    //   // Color? surfaceVariant,
    //   // Color? onSurfaceVariant,
    //   // Color? outline,
    //   // Color? outlineVariant,
    //   // Color? shadow,
    //   // Color? scrim,
    //   // Color? inverseSurface,
    //   // Color? onInverseSurface,
    //   // Color? inversePrimary,
    //   // Color? surfaceTint,
    //   // Color? primaryVariant,
    //   // Color? secondaryVariant,
    // ),
    // // Color? colorSchemeSeed,
    // // Color? dialogBackgroundColor,
    // disabledColor: Colors.yellow,
    // dividerColor: AppColors.dividerColor,
    // focusColor: Colors.deepPurpleAccent,
    // // highlightColor: Colors.pink[200],
    // hintColor: Colors.orange,
    // hoverColor: Colors.red,
    // indicatorColor: AppColors.indicatorColor,
    // // Color? primaryColor,
    // // Color? primaryColorDark,
    // // Color? primaryColorLight,
    // // MaterialColor? primarySwatch,
    // scaffoldBackgroundColor: AppColors.scaffoldBackgroundColor,
    // secondaryHeaderColor: AppColors.secondaryHeaderColor,
    // shadowColor: AppColors.shadowColor,
    // // splashColor: AppColors.splashColor,
    // unselectedWidgetColor: AppColors.unselectedWidgetColor,
    // fontFamily: AppConstants.fontFamily,
    // // List<String>? fontFamilyFallback,
    // // String? package,
    // // IconThemeData? iconTheme,
    // // IconThemeData? primaryIconTheme,
    // // TextTheme? primaryTextTheme,
    // textTheme: TextTheme(
    //   displayLarge: TextThemeStyles.displayLarge,
    //   displayMedium: TextThemeStyles.displayMedium,
    //   displaySmall: TextThemeStyles.displaySmall,
    //   headlineLarge: TextThemeStyles.headlineLarge,
    //   headlineMedium: TextThemeStyles.headlineMedium,
    //   headlineSmall: TextThemeStyles.headlineSmall,
    //   titleLarge: TextThemeStyles.titleLarge,
    //   titleMedium: TextThemeStyles.titleMedium,
    //   titleSmall: TextThemeStyles.titleSmall,
    //   bodyLarge: TextThemeStyles.bodyLarge,
    //   bodyMedium: TextThemeStyles.bodyMedium,
    //   bodySmall: TextThemeStyles.bodySmall,
    //   labelLarge: TextThemeStyles.labelLarge,
    //   labelMedium: TextThemeStyles.labelMedium,
    //   labelSmall: TextThemeStyles.labelSmall,
    // ),
    // // Typography? typography,
    // appBarTheme: AppBarThemeStyles.appBarTheme,
    // // BadgeThemeData? badgeTheme,
    // // MaterialBannerThemeData? bannerTheme,
    // // BottomAppBarTheme? bottomAppBarTheme,
    // // BottomNavigationBarThemeData? bottomNavigationBarTheme,
    // // BottomSheetThemeData? bottomSheetTheme,
    // // ButtonBarThemeData? buttonBarTheme,
    // // ButtonThemeData? buttonTheme,
    // // CardTheme? cardTheme,
    // // CheckboxThemeData? checkboxTheme,
    // // ChipThemeData? chipTheme,
    // // DataTableThemeData? dataTableTheme,
    // dialogTheme: DialogThemeStyles.dialogTheme,
    // // DividerThemeData? dividerTheme,
    // // DrawerThemeData? drawerTheme,
    // // DropdownMenuThemeData? dropdownMenuTheme,
    // elevatedButtonTheme: ButtonThemeStyles.elevatedButtonTheme,
    // // ExpansionTileThemeData? expansionTileTheme,
    // // FilledButtonThemeData? filledButtonTheme,
    // floatingActionButtonTheme: ButtonThemeStyles.floatingActionButtonTheme,
    // // IconButtonThemeData? iconButtonTheme,
    // // ListTileThemeData? listTileTheme,
    // // MenuBarThemeData? menuBarTheme,
    // // MenuButtonThemeData? menuButtonTheme,
    // // MenuThemeData? menuTheme,
    // // NavigationBarThemeData? navigationBarTheme,
    // // NavigationDrawerThemeData? navigationDrawerTheme,
    // // NavigationRailThemeData? navigationRailTheme,
    // outlinedButtonTheme: ButtonThemeStyles.outlinedButtonTheme,
    // // PopupMenuThemeData? popupMenuTheme,
    // // ProgressIndicatorThemeData? progressIndicatorTheme,
    // // RadioThemeData? radioTheme,
    // // SegmentedButtonThemeData? segmentedButtonTheme,
    // // SliderThemeData? sliderTheme,
    // // SnackBarThemeData? snackBarTheme,
    // snackBarTheme: SnackbarThemeStyles.snackBarThemeData,
    // // SwitchThemeData? switchTheme,
    // // TabBarTheme? tabBarTheme,
    // textButtonTheme: ButtonThemeStyles.textButtonTheme,
    // // TextSelectionThemeData? textSelectionTheme,
    // // TimePickerThemeData? timePickerTheme,
    // // ToggleButtonsThemeData? toggleButtonsTheme,
    // // TooltipThemeData? tooltipTheme,
  );

  // CONFIG - DARK THEME
  static final darkTheme = ThemeData();
}
